-- -----------     << Trabalho Final - Tema 1 >>     -------------------
-- 
--                    SCRIPT DE APAGA
-- 
-- Data Criacao ...........: 02/12/2023
-- Autor(es) ..............: Caio Santos e Débora Moreira
-- Banco de Dados .........: MySQL
-- Base de Dados(nome) ...: TF_1C1_caiosantos
-- 
-- Data Ultima Alteracao ..: 
--
-- PROJETO => 01 Base de Dados
--         => 30 Tabelas
-- 
-- -----------------------------------------------------------------

USE TF_1C1_caiosantos;

DROP TABLE IF EXISTS CONTRATA;
DROP TABLE IF EXISTS ENTREGA;
DROP TABLE IF EXISTS VENDEDOR_LEADE;
DROP TABLE IF EXISTS VENDEDOR_CLIENTE;
DROP TABLE IF EXISTS LOJA_GASTO_EXTRA;
DROP TABLE IF EXISTS GASTO_EXTRA;
DROP TABLE IF EXISTS TIPO_GASTO_EXTRA;
DROP TABLE IF EXISTS PRODUTOSVENDIDOS;
DROP TABLE IF EXISTS PRODUTOSCOMPRADOS;
DROP TABLE IF EXISTS COMPRA;
DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS CATEGORIAPRODUTOFORNECEDOR;
DROP TABLE IF EXISTS ESTOQUE_PRODUTO;
DROP TABLE IF EXISTS ESTOQUE;

ALTER TABLE FUNCIONARIO
DROP FOREIGN KEY FK_FUNCIONARIO_3;

DROP TABLE IF EXISTS LOJA;
DROP TABLE IF EXISTS PRODUTO;
DROP TABLE IF EXISTS CATEGORIAPRODUTO;
DROP TABLE IF EXISTS PESSOAJURIDICA;
DROP TABLE IF EXISTS PESSOAFISICA;
DROP TABLE IF EXISTS VENDA;
DROP TABLE IF EXISTS VENDEDOR;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CARGO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS LEADE;
DROP TABLE IF EXISTS TERCEIRIZADO;
DROP TABLE IF EXISTS TIPOORIGEM;
DROP TABLE IF EXISTS CATEGORIATERCEIRIZADO;
DROP TABLE IF EXISTS TELEFONE;
