-- -----------     << Trabalho Final - Tema 1 >>     -------------------
-- 
--                    SCRIPT DE APAGA
-- 
-- Data Criacao ...........: 15/12/2023
-- Autor(es) ..............: Caio Santos, Débora Moreira, Gabriel Freitas Balbino e Hugo Aragao de Oliveira
-- Banco de Dados .........: MySQL
-- Base de Dados(nome) ...: TF_1C_caiosantos
-- 
-- Data Ultima Alteracao ..: 
--
-- PROJETO => 01 Base de Dados
--         => 30 Tabelas
-- 
-- -----------------------------------------------------------------

USE TF_1C_caiosantos;

DROP TABLE CONTRATA;
DROP TABLE ENTREGA;
DROP TABLE VENDEDOR_LEADE;
DROP TABLE VENDEDOR_CLIENTE;
DROP TABLE LOJA_GASTO_EXTRA;
DROP TABLE GASTO_EXTRA;
DROP TABLE TIPO_GASTO_EXTRA;
DROP TABLE PRODUTOSVENDIDOS;
DROP TABLE PRODUTOSCOMPRADOS;
DROP TABLE COMPRA;
DROP TABLE FORNECEDOR;
DROP TABLE CATEGORIAPRODUTOFORNECEDOR;
DROP TABLE ESTOQUE_PRODUTO;
DROP TABLE ESTOQUE;

ALTER TABLE FUNCIONARIO
DROP FOREIGN KEY FK_FUNCIONARIO_3;

DROP TABLE LOJA;
DROP TABLE PRODUTO;
DROP TABLE CATEGORIAPRODUTO;
DROP TABLE PESSOAJURIDICA;
DROP TABLE PESSOAFISICA;
DROP TABLE VENDA;
DROP TABLE VENDEDOR;
DROP TABLE FUNCIONARIO;
DROP TABLE CARGO;
DROP TABLE CLIENTE;
DROP TABLE PESSOA;
DROP TABLE LEADE;
DROP TABLE TERCEIRIZADO;
DROP TABLE TIPOORIGEM;
DROP TABLE CATEGORIATERCEIRIZADO;
DROP TABLE TELEFONE;
