-- -----------     << Trabalho Final - Tema 1 >>     -------------------
-- 
--                    SCRIPT DE CRIACAO (DDL)
-- 
-- Data Criacao ...........: 02/12/2023
-- Autor(es) ..............: Caio Santos e Débora Moreira
-- Banco de Dados .........: MySQL
-- Base de Dados(nome) ...: TF_1C1_caiosantos
-- 
-- Ultimas Alteracoes:
--   08/12/2023 => Exclui tabela HISTORICOCLIENTE e adiciona tabelas VENDEDOR_LEAD e VENDEDOR_CLIENTE.
--              => Adiciona script de alter table para Loja.
--   11/12/2018 => Exclui tabela de fluxo de caixa e cria as seguintes tabelas:
--                 	COMPRA, ESTOQUE_PRODUTO, LOJA_GASTO_EXTRA, GASTO_EXTRA e TIPO_GASTO_EXTRA 
--
-- PROJETO => 01 Base de Dados
--         => 30 Tabelas
-- 
-- -----------------------------------------------------------------

-- BASE DE DADOS
CREATE DATABASE
  IF NOT EXISTS TF_1C1_caiosantos;

USE TF_1C1_caiosantos;


-- TABELAS

/* Lógico_1: */

CREATE TABLE IF NOT EXISTS TELEFONE(
    telefone_PK INTEGER AUTO_INCREMENT,
    telefone CHAR(12),
    
    CONSTRAINT TELEFONE_PK PRIMARY KEY (telefone_PK)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORIATERCEIRIZADO (
    idCategoriaTerceirizado INTEGER AUTO_INCREMENT,
    nome CHAR(25) NOT NULL,
    
    CONSTRAINT CATEGORIATERCEIRIZADO_PK PRIMARY KEY (idCategoriaTerceirizado)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS TIPOORIGEM (
    idTipoOrigem INTEGER AUTO_INCREMENT,
    nome CHAR(25) NOT NULL,
    
    CONSTRAINT TIPOORIGEM_PK PRIMARY KEY (idTipoOrigem)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS TERCEIRIZADO (
    idTerceirizado INTEGER AUTO_INCREMENT,
    idCategoriaTerceirizado INTEGER NOT NULL,
    contato CHAR(12) NOT NULL,
    nome CHAR(50) NOT NULL,
    
    CONSTRAINT TERCEIRIZADO_PK PRIMARY KEY (idTerceirizado),
    CONSTRAINT TERCEIRIZADO_CATEGORIATERCEIRADO_FK FOREIGN KEY (idCategoriaTerceirizado) REFERENCES CATEGORIATERCEIRIZADO (idCategoriaTerceirizado) ON DELETE RESTRICT
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS LEADE (
    idLeade INTEGER AUTO_INCREMENT,
    dataNascimento TIMESTAMP,
    telefone_PK INTEGER,
    email CHAR(50),
    usuarioInstagram CHAR(25),
    idTipoOrigem INTEGER NOT NULL,


    CONSTRAINT PK_Leade PRIMARY KEY (idLeade),
    CONSTRAINT FK_Leade_1 FOREIGN KEY (telefone_PK)
    REFERENCES TELEFONE (telefone_PK),
    CONSTRAINT FK_Leade_2 FOREIGN KEY (idTipoOrigem)
    REFERENCES TIPOORIGEM (idTipoOrigem)
    ON DELETE CASCADE
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS PESSOA (
    cpf CHAR(11),
    numero INT(6) NOT NULL,
    logradouro CHAR(50) NOT NULL,
    complemento CHAR(50),
    bairro CHAR(50) NOT NULL,
    cidade CHAR(50) NOT NULL,
    estado CHAR(50) NOT NULL,
    telefone_PK INTEGER NOT NULL,
    dataNascimento TIMESTAMP NOT NULL,
    email CHAR(50),
    nome CHAR(50) NOT NULL,
    genero CHAR(1) NOT NULL,

    CONSTRAINT PK_PESSOA PRIMARY KEY (cpf),
    CONSTRAINT FK_PESSOA_1 FOREIGN KEY (telefone_PK)
    REFERENCES TELEFONE (telefone_PK)
    ON DELETE NO ACTION,
    CONSTRAINT UNIQUE_PESSOA UNIQUE (email)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS CLIENTE (
    idCliente INTEGER AUTO_INCREMENT,
    idLeade INTEGER,
    cpf CHAR(11) NOT NULL,

    CONSTRAINT CLIENTE_PK PRIMARY KEY (idCliente),
    CONSTRAINT CLIENTE_UNIQUE UNIQUE (cpf),
    CONSTRAINT FK_CLIENTE_1 FOREIGN KEY (cpf)
    REFERENCES PESSOA (cpf),
    CONSTRAINT FK_CLIENTE_2 FOREIGN KEY (idLeade)
    REFERENCES LEADE (idLeade)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS CARGO (
    idCargo INTEGER AUTO_INCREMENT,
    nome CHAR(25) NOT NULL,

    CONSTRAINT CARGO_PK PRIMARY KEY (idCargo)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS LOJA (
    idLoja INTEGER AUTO_INCREMENT,
    bairro CHAR(50) NOT NULL,
    numero INT(6) NOT NULL,
    estado CHAR(50) NOT NULL,
    cidade CHAR(50) NOT NULL,
    complemento CHAR(50),
    logradouro CHAR(50) NOT NULL,
    telefone_PK INTEGER NOT NULL,
    gerente INTEGER,

    CONSTRAINT LOJA_PK PRIMARY KEY (idLoja),
    
    CONSTRAINT UNIQUE_LOJA UNIQUE (gerente),

    CONSTRAINT FK_LOJA_1 FOREIGN KEY (telefone_PK)
    REFERENCES telefone (telefone_PK)
    ON DELETE NO ACTION
) Engine = InnoDB;

CREATE TABLE IF NOT EXISTS FUNCIONARIO (
    idFuncionario INTEGER AUTO_INCREMENT,
    salarioBase INTEGER NOT NULL,
    comissao INTEGER NOT NULL,
    cpf CHAR(11) NOT NULL,
    idCargo INTEGER NOT NULL,
    idLoja INTEGER NOT NULL,

    CONSTRAINT FUNCIONARIO_PK PRIMARY KEY (idFuncionario),
    CONSTRAINT FUNCIONARIO_UNIQUE UNIQUE (cpf),
    CONSTRAINT FK_FUNCIONARIO_1 FOREIGN KEY (cpf)
    REFERENCES PESSOA (cpf)
    ON DELETE CASCADE,
 
    CONSTRAINT FK_FUNCIONARIO_2 FOREIGN KEY (idCargo)
    REFERENCES CARGO (idCargo)
    ON DELETE RESTRICT,

    CONSTRAINT FK_FUNCIONARIO_3 FOREIGN KEY (idLoja)
    REFERENCES LOJA (idLoja)
    ON DELETE CASCADE
)Engine = InnoDB;

ALTER TABLE LOJA
ADD CONSTRAINT FOREIGN KEY (gerente) REFERENCES FUNCIONARIO (idFuncionario)
ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS VENDEDOR (
    idVendedor INTEGER AUTO_INCREMENT,
    idFuncionario INTEGER NOT NULL,
    
    CONSTRAINT VENDEDOR_PK PRIMARY KEY (idVendedor),
    CONSTRAINT VENDEDOR_UNIQUE UNIQUE (idFuncionario),
    CONSTRAINT FK_VENDEDOR_1 FOREIGN KEY (idFuncionario)
    REFERENCES FUNCIONARIO (idFuncionario)
    ON DELETE CASCADE
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS VENDA (
    idVenda INTEGER AUTO_INCREMENT,
    idCliente INTEGER NOT NULL,
    valorTotal FLOAT NOT NULL,
    dataVenda TIMESTAMP NOT NULL,
    idVendedor INTEGER NOT NULL,

    CONSTRAINT VENDA_PK PRIMARY KEY (idVenda),
    CONSTRAINT FK_VENDA_1 FOREIGN KEY (idVendedor)
    REFERENCES VENDEDOR (idVendedor)
    ON DELETE CASCADE,
 
    CONSTRAINT FK_VENDA_2 FOREIGN KEY (idCliente)
    REFERENCES CLIENTE (idCliente)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS PESSOAFISICA (
    idPessoaFisica INTEGER AUTO_INCREMENT,
    sexo CHAR(1) NOT NULL,
    estadoCivil CHAR(20) NOT NULL,
    rg CHAR(25) NOT NULL,
    idCliente INTEGER,
    
    CONSTRAINT PESSOAFISICA_PK PRIMARY KEY (idPessoaFisica, idCliente),
    CONSTRAINT FK_PESSOAFISICA_1 FOREIGN KEY (idCliente)
    REFERENCES CLIENTE (idCliente)
    ON DELETE CASCADE,
    CONSTRAINT PESSOAFISICA_UNIQUE UNIQUE (rg)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS PESSOAJURIDICA (
    cnpj CHAR(14),
    razaoSocial CHAR(50) NOT NULL,
    nomeFantasia CHAR(50) NOT NULL,
    inscricaoEstadual CHAR(9) NOT NULL,
    inscricaoMunicipal CHAR(11) NOT NULL,
    idCliente INTEGER,

    CONSTRAINT PESSOAJURIDICA_PK PRIMARY KEY (cnpj, idCliente),

    CONSTRAINT FK_PESSOAJURIDICA_1 FOREIGN KEY (idCliente)
    REFERENCES CLIENTE (idCliente)
    ON DELETE CASCADE
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORIAPRODUTO (
    idCategoriaProduto INTEGER AUTO_INCREMENT,
    nome CHAR(25) NOT NULL,

    CONSTRAINT CATEGORIAPRODUTO_PK PRIMARY KEY (idCategoriaProduto)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS PRODUTO (
    idProduto INTEGER AUTO_INCREMENT,
    descricao CHAR(50) NOT NULL,
    valorPorMetro FLOAT NOT NULL,
    FK_CATEGORIAPRODUTO_idCategoriaProduto INTEGER NOT NULL,
    
    CONSTRAINT PRODUTO_PK PRIMARY KEY (idProduto),

    CONSTRAINT FK_PRODUTO_1 FOREIGN KEY (FK_CATEGORIAPRODUTO_idCategoriaProduto)
    REFERENCES CATEGORIAPRODUTO (idCategoriaProduto)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS ESTOQUE (
    idEstoque INTEGER AUTO_INCREMENT,
    idLoja INTEGER NOT NULL,
    capacidade INTEGER NOT NULL,

    CONSTRAINT ESTOQUE_PK PRIMARY KEY (idEstoque),

    CONSTRAINT FK_ESTOQUE_1 FOREIGN KEY (idLoja)
    REFERENCES LOJA (idLoja)
    ON DELETE CASCADE
) Engine = InnoDB;

CREATE TABLE IF NOT EXISTS ESTOQUE_PRODUTO (
	idEstoque INTEGER,
    idProduto INTEGER, 
    quantidade INTEGER NOT NULL,
    
    CONSTRAINT ESTOQUE_PRODUTO_PK PRIMARY KEY (idEstoque, idProduto),
    CONSTRAINT ESTOQUE_PRODUTO_FK_1 FOREIGN KEY (idEstoque)
    REFERENCES ESTOQUE (idEstoque),
    CONSTRAINT ESTOQUE_PRODUTO_FK_2 FOREIGN KEY (idProduto)
    REFERENCES PRODUTO (idProduto)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS CATEGORIAPRODUTOFORNECEDOR (
    idCategoriaProdutoFornecedor INTEGER AUTO_INCREMENT,
    idCategoriaProduto INTEGER NOT NULL,

    CONSTRAINT CATEGORIAPRODUTOFORNECEDOR_PK PRIMARY KEY (idCategoriaProdutoFornecedor),
    CONSTRAINT CATEGORIAPRODUTOFORNECEDOR_CATEGORIAPRODUTO_FK FOREIGN KEY (idCategoriaProduto) REFERENCES CATEGORIAPRODUTO (idCategoriaProduto) ON DELETE RESTRICT
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS FORNECEDOR (
    idFornecedor INTEGER AUTO_INCREMENT,
    contato CHAR(12) NOT NULL,
    nomeRepresentante CHAR(50) NOT NULL,
    idCategoriaProduto INTEGER NOT NULL,

    CONSTRAINT FORNECEDOR_PK PRIMARY KEY (idFornecedor),

    CONSTRAINT FK_FORNECEDOR_2 FOREIGN KEY (idCategoriaProduto)
    REFERENCES CATEGORIAPRODUTOFORNECEDOR (idCategoriaProdutoFornecedor)
    ON DELETE NO ACTION
) Engine = InnoDB;

CREATE TABLE IF NOT EXISTS COMPRA (
    idCompra INTEGER AUTO_INCREMENT,
    valorTotal FLOAT NOT NULL,
    dataCompra TIMESTAMP NOT NULL,
    idLoja INTEGER NOT NULL,
    idFornecedor INTEGER NOT NULL,

    CONSTRAINT COMPRA_PK PRIMARY KEY (idCompra),
    CONSTRAINT FK_COMPRA_1 FOREIGN KEY (idLoja)
    REFERENCES LOJA (idLoja)
    ON DELETE CASCADE,
    
     CONSTRAINT FK_COMPRA_2 FOREIGN KEY (idFornecedor)
     REFERENCES FORNECEDOR (idFornecedor)
     ON DELETE RESTRICT
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS PRODUTOSCOMPRADOS (
    idCompra INTEGER,
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    idEstoque INTEGER NOT NULL,
    idProduto INTEGER NOT NULL,

    CONSTRAINT PRODUTOSCOMPRADOS_PK PRIMARY KEY (idCompra, idProduto),
    CONSTRAINT PRODUTOSCOMPRADOS_ESTOQUE_FK FOREIGN KEY (idEstoque) REFERENCES ESTOQUE (idEstoque) ON DELETE RESTRICT,
    CONSTRAINT PRODUTOSCOMPRADOS_LOJA_FK FOREIGN KEY (idCompra) REFERENCES COMPRA (idCompra) ON DELETE RESTRICT,
    CONSTRAINT PRODUTOSCOMPRADOS_PRODUTO_FK FOREIGN KEY (idProduto) REFERENCES PRODUTO (idProduto) ON DELETE RESTRICT
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS PRODUTOSVENDIDOS (
    quantidade INTEGER NOT NULL CHECK (quantidade > 0),
    idEstoque INTEGER NOT NULL,
    idProduto INTEGER NOT NULL,
    idVenda INTEGER NOT NULL,
    
    CONSTRAINT PRODUTOSVENDIDOS_PK PRIMARY KEY (idProduto, idVenda),
    CONSTRAINT PRODUTOSVENDIDOS_ESTOQUE_FK FOREIGN KEY (idEstoque) REFERENCES ESTOQUE (idEstoque) ON DELETE RESTRICT,
    CONSTRAINT PRODUTOSVENDIDOS_PRODUTO_FK FOREIGN KEY (idProduto) REFERENCES PRODUTO (idProduto) ON DELETE RESTRICT,
    CONSTRAINT PRODUTOSVENDIDOS_VENDA_FK FOREIGN KEY (idVenda) REFERENCES VENDA (idVenda) ON DELETE RESTRICT
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS TIPO_GASTO_EXTRA (
    idTipoGasto INTEGER AUTO_INCREMENT,
    descricao VARCHAR(255) NOT NULL,

    CONSTRAINT TIPO_GASTO_EXTRA_PK PRIMARY KEY (idTipoGasto)
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS GASTO_EXTRA (
    idGastoExtra INTEGER AUTO_INCREMENT,
    idTipoGasto INTEGER NOT NULL,
    dataGastoExtra TIMESTAMP NOT NULL,
    valorGastoExtra FLOAT NOT NULL,

    CONSTRAINT GASTO_EXTRA_PK PRIMARY KEY (idGastoExtra),

    CONSTRAINT FK_GASTO_EXTRA_1 FOREIGN KEY (idTipoGasto)
    REFERENCES TIPO_GASTO_EXTRA (idTipoGasto)
    ON DELETE RESTRICT
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS LOJA_GASTO_EXTRA (
    idLoja INTEGER NOT NULL,
    idGastoExtra INTEGER NOT NULL,
    idLojaGastoExtra INTEGER AUTO_INCREMENT,

    CONSTRAINT LOJA_GASTO_EXTRA_PK PRIMARY KEY (idLojaGastoExtra),

    CONSTRAINT FK_LOJA_GASTO_EXTRA_1 FOREIGN KEY (idGastoExtra)
    REFERENCES GASTO_EXTRA (idGastoExtra)
    ON DELETE RESTRICT,
 
    CONSTRAINT FK_LOJA_GASTO_EXTRA_2 FOREIGN KEY (idLoja)
    REFERENCES LOJA (idLoja)
    ON DELETE RESTRICT
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS VENDEDOR_LEADE (
    idLeade INTEGER,
    descricaoAtendimento CHAR(255) NOT NULL,
    idVendedor INTEGER,

    CONSTRAINT VENDEDOR_LEADE_PK PRIMARY KEY (idLeade, idVendedor),
    CONSTRAINT FK_VENDEDOR_LEADE_1 FOREIGN KEY (idLeade)
    REFERENCES LEADE (idLeade),
    CONSTRAINT FK_VENDEDOR_LEADE_2 FOREIGN KEY (idVendedor)
    REFERENCES VENDEDOR (idVendedor)    
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS VENDEDOR_CLIENTE (
    idCliente INTEGER,
    descricaoAtendimento CHAR(255) NOT NULL,
    idVendedor INTEGER,

    CONSTRAINT VENDEDOR_CLIENTE_PK PRIMARY KEY (idCliente, idVendedor),
    CONSTRAINT FK_VENDEDOR_CLIENTE_1 FOREIGN KEY (idCliente)
    REFERENCES CLIENTE (idCliente),
    CONSTRAINT FK_VENDEDOR_CLIENTE_2 FOREIGN KEY (idVendedor)
    REFERENCES VENDEDOR (idVendedor)    
)Engine = InnoDB;

CREATE TABLE IF NOT EXISTS ENTREGA (
    idEntrega INTEGER AUTO_INCREMENT,
    idVenda INTEGER NOT NULL,
    dataPrevista TIMESTAMP NOT NULL,
    dataRealizada TIMESTAMP NOT NULL,
    idTerceirizado INTEGER NOT NULL,
    valorEntrega FLOAT NOT NULL,

    CONSTRAINT ENTREGA_PK PRIMARY KEY (idEntrega),
    CONSTRAINT ENTREGA_VENDA_FK FOREIGN KEY (idVenda) REFERENCES VENDA (idVenda) ON DELETE RESTRICT,
    CONSTRAINT ENTREGA_TERCEIRIZADO_FK FOREIGN KEY (idTerceirizado) REFERENCES TERCEIRIZADO (idTerceirizado) ON DELETE RESTRICT
)Engine = InnoDB;


CREATE TABLE IF NOT EXISTS CONTRATA (
    idContrata INTEGER AUTO_INCREMENT,
    idLoja INTEGER NOT NULL,
    idTerceirizado INTEGER NOT NULL,
    descricaoServico CHAR(255) NOT NULL,

    CONSTRAINT CONTRATA_PK PRIMARY KEY (idContrata),
    CONSTRAINT CONTRATA_LOJA_FK FOREIGN KEY (idLoja) REFERENCES LOJA (idLoja) ON DELETE RESTRICT,
    CONSTRAINT CONTRATA_TERCEIRIZADO_FK FOREIGN KEY (idTerceirizado) REFERENCES TERCEIRIZADO (idTerceirizado) ON DELETE RESTRICT
)Engine = InnoDB;